syntax <- c(
  # Define random intercepts
  "iamsup =~ 1*amsup1 + 1*amsup2 + 1*amsup3 + 1*amsup4",
  "iafsup =~ 1*afsup1 + 1*afsup2 + 1*afsup3 + 1*afsup4",
  "ide =~ 1*de1 + 1*de2 + 1*de3 + 1*de4",
  # RI covariances
  "iamsup ~~ c(iamsupWiafsupG, iamsupWiafsupB)*iafsup",
  "iamsup ~~ c(iamsupWideG, iamsupWideB)*ide",
  "iafsup ~~ c(iafsupWideG, iafsupWideB)*ide",
  # Center within-family deviations
  "camsup1 =~ amsup1",
  "camsup2 =~ amsup2",
  "camsup3 =~ amsup3",
  "camsup4 =~ amsup4",
  "cafsup1 =~ afsup1",
  "cafsup2 =~ afsup2",
  "cafsup3 =~ afsup3",
  "cafsup4 =~ afsup4",
  "cde1 =~ de1",
  "cde2 =~ de2",
  "cde3 =~ de3",
  "cde4 =~ de4",
  # Residuals fixed to zero
  "amsup1 ~~ 0*amsup1",
  "amsup2 ~~ 0*amsup2",
  "amsup3 ~~ 0*amsup3",
  "amsup4 ~~ 0*amsup4",
  "afsup1 ~~ 0*afsup1",
  "afsup2 ~~ 0*afsup2",
  "afsup3 ~~ 0*afsup3",
  "afsup4 ~~ 0*afsup4",
  "de1 ~~ 0*de1",
  "de2 ~~ 0*de2",
  "de3 ~~ 0*de3",
  "de4 ~~ 0*de4",
  # Latent variable means supstrained to 0
  "iamsup ~ 0*1",
  "iafsup ~ 0*1",
  "ide ~ 0*1",
  # Intercepts
  "amsup1 ~ c(mamsup1G, mamsup1B)*1",
  "amsup2 ~ c(mamsup2G, mamsup2B)*1",
  "amsup3 ~ c(mamsup3G, mamsup3B)*1",
  "amsup4 ~ c(mamsup4G, mamsup4B)*1",
  "afsup1 ~ c(mafsup1G, mafsup1B)*1",
  "afsup2 ~ c(mafsup2G, mafsup2B)*1",
  "afsup3 ~ c(mafsup3G, mafsup3B)*1",
  "afsup4 ~ c(mafsup4G, mafsup4B)*1",
  "de1 ~ c(mde1G, mde1B)*1",
  "de2 ~ c(mde2G, mde2B)*1",
  "de3 ~ c(mde3G, mde3B)*1",
  "de4 ~ c(mde4G, mde4B)*1",
  # Variances
  "iamsup ~~ c(vamsupG, vamsupB)*iamsup",
  "iafsup ~~ c(vafsupG, vafsupB)*iafsup",
  "ide ~~ c(vdeG, vdeB)*ide",
  "camsup1 ~~ c(vcamsup1G, vcamsup1B)*camsup1",
  "cafsup1 ~~ c(vcafsup1G, vcafsup1B)*cafsup1",
  "cde1 ~~ c(vcde1G, vcde1B)*cde1",
  # Residual variances
  "camsup2 ~~ c(vcamsup2G, vcamsup2B)*camsup2",
  "camsup3 ~~ c(vcamsup3G, vcamsup3B)*camsup3",
  "camsup4 ~~ c(vcamsup4G, vcamsup4B)*camsup4",
  "cafsup2 ~~ c(vcafsup2G, vcafsup2B)*cafsup2",
  "cafsup3 ~~ c(vcafsup3G, vcafsup3B)*cafsup3",
  "cafsup4 ~~ c(vcafsup4G, vcafsup4B)*cafsup4",
  "cde2 ~~ c(vcde2G, vcde2B)*cde2",
  "cde3 ~~ c(vcde3G, vcde3B)*cde3",
  "cde4 ~~ c(vcde4G, vcde4B)*cde4",
  # Covariances between RI and variance of observed to 0
  "iamsup ~~ 0*camsup1 + 0*camsup2 + 0*camsup3 + 0*camsup4 + 0*cafsup1 + 0*cafsup2 + 0*cafsup3 + 0*cafsup4 + 0*cde1 + 0*cde2 + 0*cde3 + 0*cde4",
  "iafsup ~~ 0*camsup1 + 0*camsup2 + 0*camsup3 + 0*camsup4 + 0*cafsup1 + 0*cafsup2 + 0*cafsup3 + 0*cafsup4 + 0*cde1 + 0*cde2 + 0*cde3 + 0*cde4",
  "ide ~~ 0*camsup1 + 0*camsup2 + 0*camsup3 + 0*camsup4 + 0*cafsup1 + 0*cafsup2 + 0*cafsup3 + 0*cafsup4 + 0*cde1 + 0*cde2 + 0*cde3 + 0*cde4",
  # Within-time corr
  "camsup1 ~~ c(camsup1Wcafsup1G, camsup1Wcafsup1B)*cafsup1",
  "camsup1 ~~ c(camsup1Wcde1G, camsup1Wcde1B)*cde1",
  "cafsup1 ~~ c(cafsup1Wcde1G, cafsup1Wcde1B)*cde1",
  "camsup2 ~~ c(camsupWcafsupG, camsupWcafsupB)*cafsup2",
  "camsup2 ~~ c(camsupWcdeG, camsupWcdeB)*cde2",
  "cafsup2 ~~ c(cafsupWcdeG, cafsupWcdeB)*cde2",
  "camsup3 ~~ c(camsupWcafsupG, camsupWcafsupB)*cafsup3",
  "camsup3 ~~ c(camsupWcdeG, camsupWcdeB)*cde3",
  "cafsup3 ~~ c(cafsupWcdeG, cafsupWcdeB)*cde3",
  "camsup4 ~~ c(camsupWcafsupG, camsupWcafsupB)*cafsup4",
  "camsup4 ~~ c(camsupWcdeG, camsupWcdeB)*cde4",
  "cafsup4 ~~ c(cafsupWcdeG, cafsupWcdeB)*cde4",
  # Stability
  "camsup2 ~ c(camsupOcamsupG, camsupOcamsupB)*camsup1",
  "camsup3 ~ c(camsupOcamsupG, camsupOcamsupB)*camsup2",
  "camsup4 ~ c(camsupOcamsupG, camsupOcamsupB)*camsup3",
  "cafsup2 ~ c(cafsupOcafsupG, cafsupOcafsupB)*cafsup1",
  "cafsup3 ~ c(cafsupOcafsupG, cafsupOcafsupB)*cafsup2",
  "cafsup4 ~ c(cafsupOcafsupG, cafsupOcafsupB)*cafsup3",
  "cde2 ~ c(cdeOcdeG, cdeOcdeB)*cde1",
  "cde3 ~ c(cdeOcdeG, cdeOcdeB)*cde2",
  "cde4 ~ c(cdeOcdeG, cdeOcdeB)*cde3",
  # Crosspaths
  "cde2 ~ c(mg, mb)*camsup1",
  "cde3 ~ c(mg, mb)*camsup2",
  "cde4 ~ c(mg, mb)*camsup3",
  "cde2 ~ c(fg, fb)*cafsup1",
  "cde3 ~ c(fg, fb)*cafsup2",
  "cde4 ~ c(fg, fb)*cafsup3",
  "camsup2 ~ c(camsupOcdeG, camsupOcdeB)*cde1",
  "camsup3 ~ c(camsupOcdeG, camsupOcdeB)*cde2",
  "camsup4 ~ c(camsupOcdeG, camsupOcdeB)*cde3",
  "cafsup2 ~ c(cafsupOcdeG, cafsupOcdeB)*cde1",
  "cafsup3 ~ c(cafsupOcdeG, cafsupOcdeB)*cde2",
  "cafsup4 ~ c(cafsupOcdeG, cafsupOcdeB)*cde3",
  "camsup2 ~ c(camsupOcafsupG, camsupOcafsupB)*cafsup1",
  "camsup3 ~ c(camsupOcafsupG, camsupOcafsupB)*cafsup2",
  "camsup4 ~ c(camsupOcafsupG, camsupOcafsupB)*cafsup3",
  "cafsup2 ~ c(cafsupOcamsupG, cafsupOcamsupB)*camsup1",
  "cafsup3 ~ c(cafsupOcamsupG, cafsupOcamsupB)*camsup2",
  "cafsup4 ~ c(cafsupOcamsupG, cafsupOcamsupB)*camsup3"
)